# Site settings
title: "Gondor : The Groovy DSL for HTCondor DAGman Workflows"
email: jimwhite@uw.edu
description: "Groovy Condor : High Throughput Computing in High Style"
baseurl: "/Gondor"
# url: "http://azachary777.github.io/Gondor"
twitter_username: oohtml
github_username:  jimwhite

# Build settings
markdown: redcarpet
permalink: pretty
safe: true
lsi: false
highlighter : pygments

syntax-highlighting:
  enabled : true
  css: syntax.css
